// vite-esm-sfc/src/components/Counter.vue
<template>
  <h1>Counter {{ no }}: {{ counter }}</h1>
</template>

<script>
export default {
  name: 'Counter',
  props: {
    no: Number,
    countForward: Boolean,
    initialValue: Number
  },
  data() {
    return {
      counter: this.initialValue
    }
  },
  mounted() {
    setInterval(() => {
      if (this.countForward) {
        this.counter++
      } else {
        this.counter--
      }
    }, 1000)
  }
}
</script>

// vite-esm-jsx/src/components/Counter.jsx
export default {
  name: 'Counter',
  props: {
    no: Number,
    countForward: Boolean,
    initialValue: Number
  },
  render() {
    return <h1>Counter {this.no}: {this.counter}</h1>
  },
  data() {
    return {
      counter: this.initialValue
    }
  },
  mounted() {
    setInterval(() => {
      if (this.countForward) {
        this.counter++
      } else {
        this.counter--
      }
    }, 1000)
  }
}
